### ISSUE TITLE
Display AT message in transaction details

### ISSUE THREAD

**Issue by llybin** [llybin/burst_explorer#43]
[Forwarded from Algirdas]
Can you add messeges to your explorer, AT sends messeges but it can be seen, http://explorer.testnet.burst.devtrue.net/tx/8754897640405689599

messege at hexidecimels

http://testnet.getburst.net:6876/burst?requestType=readMessage&transaction=8754897640405689599

**Comment by shefass** [comment]
ATs can send messages, it is a good way to communicate/give feedback for the client. It was cool if people can read messages at explorer, it did an auto conversion from hexadecimal.
